### PR TITLE
Upgrade to latest release (working on OSX) 1.6.5

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by isuruf** [comment]
Thanks. Feel free to add yourself as a maintainer.

**Comment by isuruf** [comment]
Also, should pari be pinned?

**Comment by saraedum** [comment]
The Pari dependency is really quite odd…

**Comment by saraedum** [comment]
@isuruf Could you have a look at that weird CircleCI error?

**Comment by saraedum** [comment]
I don't think we need pinning here btw.

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Hmm, osx fails

**Comment by saraedum** [comment]
"Cannot allocate memory" is a bit bizarre.

**Comment by isuruf** [comment]
https://github.com/sagemath/cysignals/issues/68#issuecomment-368326682

**Comment by saraedum** [comment]
So…1.6.6 instead?

**Comment by isuruf** [comment]
What does sage use?

**Comment by saraedum** [comment]
1.6.5

**Comment by isuruf** [comment]
We can upgrade to 1.6.5 then.

**Pull request merged**
